wiki:
    type: "farm" # "standalone" or "farm", optional, defaults to "standalone"
    path: "/home/dsavuljesku/workspace/w"
queue: "redis"
database:
    dbserver: "127.0.0.1" # Optional, defaults to localhost
    dbport: 3306 # Optional, defaults to 3306
    dbname: "galaxy"
    dbuser: "dejan"
    dbpassword: "Marshall90&"
    dbprefix: "" # Optional, defaults to ""
redis:
    host: "127.0.0.1"
    port: 6379
runjobs:
    maxtime: 30         # Maximum TTL of a runJobs.php (Per wiki, per cycle) - Seconds, optional
    maxjobs: 50        # Maximum number of jobs to run in a single call, optional
    maxparallel: 20      # Maximum number of jobs to run in parallel (default: 1 for standalone, 10 for farm), optional
farm: # Whole section is optional
    # Exclude list has priority over include list
    include-instances: []
    exclude-instances: []
