#!/bin/bash

for i in "$@"; do
  case $i in
    --profile=upgrade)
      UPGRADE_ACTION="/app/bin/upgrade-pipeline"
      ;;
    --profile=upgrade-force)
      UPGRADE_ACTION="/app/bin/upgrade-pipeline -f"
      ;;
    --profile=*)
      echo "Unknown profile ${i#*=}"
      exit 1
      ;;
    *)
      DOCKER_ARGS+=("$i")
      ;;
  esac
done

export UPGRADE_ACTION=${UPGRADE_ACTION:-"sleep 1"}

export TZ=$(readlink /etc/localtime 2>/dev/null | sed 's|.*/zoneinfo/||')

source .env

EXTENDED_TOOLS=""

case "${EDITION}" in
	glacier)
		WIKI_IMAGE=bluespicegalaxy/wiki:${VERSION}
		;;
	sky|sapphire)
		EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.collabpads-service.yml"
		WIKI_IMAGE=docker.bluespice.com/bluespice-galaxy-${EDITION}/wiki:${VERSION}

		if [[ $(docker images -q ${WIKI_IMAGE}) ]]; then
			echo "Image ${WIKI_IMAGE} found locally."
		elif [[ ! $(grep 'docker.bluespice.com' $HOME/.docker/config.json) ]]; then
			echo "In order to access our ${EDITION}-Image please login to docker.bluespice.com"
			docker login docker.bluespice.com
			if [[ ! $(grep 'docker.bluespice.com' $HOME/.docker/config.json) ]]; then
			echo -e "\n-------------\n"
			echo "Please contact support@hallowelt.com for your Credentials against docker.bluespice.com"
			echo -e "\n-------------\n"
			exit
			fi
		fi
		;;
	*)
		echo "Unknown EDITION '${EDITION}'. Supported editions: glacier, sky, sapphire"
		exit 1
		;;
esac
if [ "${ANTIVIRUS}" == "true" ]; then
	EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.clamav-antivirus.yml"
fi
if [ "${CHAT}" == "true" ]; then
	EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.chat.yml"
	if [ "${AI}" == "true" ]; then
		EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.ai.yml"
	fi
fi
if [ "${LETSENCRYPT}" == "true" ]; then
	EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.proxy-letsencrypt.yml"
fi
EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.proxy.yml"

if [ -f docker-compose.override.yml ]; then
       EXTENDED_TOOLS="${EXTENDED_TOOLS} -f docker-compose.override.yml"
fi
##allow custom services repo for testing
if [ -z "${BLUESPICE_SERVICE_REPOSITORY}" ] && [ -n "${SERVICES_REPOSITORY_PATH}" ]; then
	BLUESPICE_SERVICE_REPOSITORY=${SERVICES_REPOSITORY_PATH}
fi
BLUESPICE_SERVICE_REPOSITORY=${BLUESPICE_SERVICE_REPOSITORY:-bluespice}
##allow custom wiki image for testing
if [ -n "${BLUESPICE_WIKI_IMAGE}" ]; then
	WIKI_IMAGE=${BLUESPICE_WIKI_IMAGE}
fi

if [ ! -d ${DATADIR}/.secrets ]; then
	echo "Preparing Secrets"
	BLUESPICE_WIKI_IMAGE=${WIKI_IMAGE}	\
	BLUESPICE_SERVICE_REPOSITORY=${BLUESPICE_SERVICE_REPOSITORY} \
		docker compose \
		-f docker-compose.helper-service.yml \
		-f docker-compose.secrets.yml \
		-f docker-compose.main.yml \
		-f docker-compose.persistent-data-services.yml \
		-f docker-compose.stateless-services.yml \
		${EXTENDED_TOOLS} \
		up prepare
	echo "Preparation finished"
fi

	BLUESPICE_WIKI_IMAGE=${WIKI_IMAGE}	\
	BLUESPICE_SERVICE_REPOSITORY=${BLUESPICE_SERVICE_REPOSITORY} \
		docker compose \
		-f docker-compose.helper-service.yml \
		-f docker-compose.secrets.yml \
		-f docker-compose.main.yml \
		-f docker-compose.persistent-data-services.yml \
		-f docker-compose.stateless-services.yml \
		${EXTENDED_TOOLS} \
		${DOCKER_ARGS[*]}