services:

  proxy:
    image: docker.bluespice.com/bluespice/proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ${DATADIR}/proxy/conf.d:/etc/nginx/conf.d
      - ${DATADIR}/proxy/vhost.d:/etc/nginx/vhost.d
      - ${DATADIR}/proxy/html:/usr/share/nginx/html
      - ${DATADIR}/proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.nginx-proxy.nginx=true

  wiki-web:
    environment:
      VIRTUAL_HOST: ${WIKI_HOST}
      VIRTUAL_PORT: 9090

  collabpadsbackend:
    environment:
      VIRTUAL_HOST: ${WIKI_HOST}
      VIRTUAL_PATH: /_collabpads/

  diagram:
    environment:
      VIRTUAL_HOST: ${WIKI_HOST}
      VIRTUAL_PATH: /_diagram/
      VIRTUAL_PORT: 8080
      VIRTUAL_DEST: /

