name: bluespice

x-common-environment: &common-environment
  WIKI_NAME: ${WIKI_NAME}
  WIKI_LANG: ${WIKI_LANG}
  WIKI_PASSWORDSENDER: ${WIKI_PASSWORDSENDER}
  WIKI_EMERGENCYCONTACT: ${WIKI_EMERGENCYCONTACT}
  WIKI_HOST: ${WIKI_HOST}
  WIKI_PORT: ${WIKI_PORT}
  WIKI_PROTOCOL: ${WIKI_PROTOCOL}

  CACHE_HOST: ${CACHE_HOST}
  CACHE_PORT: ${CACHE_PORT}

  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  DB_HOST: ${DB_HOST}
  DB_NAME: ${DB_NAME}
  DB_PREFIX: ${DB_PREFIX}

  FORMULA_HOST: ${FORMULA_HOST}
  FORMULA_PORT: ${FORMULA_PORT}
  FORMULA_PROTOCOL: ${FORMULA_PROTOCOL}

  PAGEPREVIEW_HOST: ${PAGEPREVIEW_HOST}
  PAGEPREVIEW_PORT: ${PAGEPREVIEW_PORT}
  PAGEPREVIEW_PROTOCOL: ${PAGEPREVIEW_PROTOCOL}

  PDF_HOST: ${PDF_HOST}
  PDF_PORT: ${PDF_PORT}
  PDF_PROTOCOL: ${PDF_PROTOCOL}

  SEARCH_HOST: ${SEARCH_HOST}
  SEARCH_PORT: ${SEARCH_PORT}
  SEARCH_PROTOCOL: ${SEARCH_PROTOCOL}

  DIAGRAM_PROTOCOL: ${DIAGRAM_PROTOCOL}
  DIAGRAM_HOST: ${DIAGRAM_HOST}
  DIAGRAM_PORT: ${DIAGRAM_PORT}
  DIAGRAM_PATH: ${DIAGRAM_PATH}

  COLLABPADSBACKEND_PATH: ${COLLABPADSBACKEND_PATH}
  COLLABPADS_BACKEND_PORT: ${COLLABPADS_BACKEND_PORT}
  COLLABPADS_BACKEND_WIKI_BASEURL: ${COLLABPADS_BACKEND_WIKI_BASEURL}
  COLLABPADS_BACKEND_MONGO_DB_HOST: ${COLLABPADS_BACKEND_MONGO_DB_HOST}
  COLLABPADS_BACKEND_MONGO_DB_PORT: ${COLLABPADS_BACKEND_MONGO_DB_PORT}
  COLLABPADS_BACKEND_MONGO_DB_NAME: ${COLLABPADS_BACKEND_MONGO_DB_NAME}
  COLLABPADS_BACKEND_MONGO_DB_USER: ${COLLABPADS_BACKEND_MONGO_DB_USER}
  COLLABPADS_BACKEND_MONGO_DB_PASSWORD: ${COLLABPADS_BACKEND_MONGO_DB_PASSWORD}
  COLLABPADS_BACKEND_LOG_LEVEL: ${COLLABPADS_BACKEND_LOG_LEVEL}
  COLLABPADS_BACKEND_HTTP_CLIENT_OPTIONS: ${COLLABPADS_BACKEND_HTTP_CLIENT_OPTIONS}

  SMTP_HOST: ${SMTP_HOST}
  SMTP_PORT: ${SMTP_PORT}
  SMTP_USER: ${SMTP_USER}
  SMTP_PASS: ${SMTP_PASS}
  SMTP_ID_HOST: ${SMTP_ID_HOST}

  VERSION: ${VERSION}
  EDITION: ${EDITION}
  BACKUP_HOUR: ${BACKUP_HOUR}
  DEV_WIKI_DEBUG: ${DEV_WIKI_DEBUG}


services:
  wiki-web:
    image: docker.bluespice.com/bluespice-${EDITION}/${EDITION}:${VERSION}
    environment:
      <<: *common-environment
    command: start-web

    volumes:
      - ${DATADIR}/wiki:/data

  wiki-task:
    image: docker.bluespice.com/bluespice-${EDITION}/${EDITION}:${VERSION}
    command: ["start-task --runAll"]
    environment:
      <<: *common-environment
    volumes:
      - ${DATADIR}/wiki:/data
