version: "3.7"

services:

  letsencrypt:
    image: nginxproxy/acme-companion
    environment:
      - DEFAULT_EMAIL=${ADMIN_MAIL}
      - NGINX_PROXY_CONTAINER=proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATADIR}/letsencrypt:/etc/acme.sh
    volumes_from:
      - proxy
    depends_on:
      - proxy
