services:
  cache:
    image: ${BLUESPICE_SERVICE_REPOSITORY}/cache:${VERSION}
    restart: unless-stopped
  pdf:
    image: ${BLUESPICE_SERVICE_REPOSITORY}/pdf:${VERSION}
    restart: unless-stopped
  
  formula:
    image: ${BLUESPICE_SERVICE_REPOSITORY}/formula:${VERSION}
    restart: unless-stopped

  diagram:
    image: ${BLUESPICE_SERVICE_REPOSITORY}/diagram:${VERSION}
    restart: unless-stopped
