version: "3.7"

services:

  search:
    image: bluespice/search:${VERSION}
    volumes:
      - ${DATADIR}/search:/usr/share/opensearch/data
    healthcheck:
      test: curl -f http://localhost:9200
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  database:
    image: mariadb:10.5
    volumes:
      - ${DATADIR}/database/data:/var/lib/mysql
      - ${DATADIR}/database/logs:/var/log/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
    healthcheck:
      #See https://mariadb.com/kb/en/using-healthcheck-sh/
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  wiki-web:
    depends_on:
        database:
            condition: service_healthy
        search:
            condition: service_healthy
  wiki-task:
    depends_on:
        database:
            condition: service_healthy
        search:
            condition: service_healthy