services:
    postgresql:
      image: postgres:16
      volumes: 
        - ${DATADIR}/keycloak/database:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=keycloak
        - POSTGRES_DB=keycloak
        - POSTGRES_PASSWORD=keycloak
      networks:
        - proxy-net
      labels:
        - "traefik.enable=false"
    keycloak:
      image: quay.io/keycloak/keycloak:latest 
      command: start
      restart: always
      environment:
       - KC_HEALTH_ENABLED=true
       - KC_METRICS_ENABLED=true
       - KC_PROXY_ADDRESS_FORWARDING=true
       - KC_HOSTNAME_STRICT=false
       - KC_HOSTNAME=${WIKI_HOST}
       - KC_PROXY=edge
       - KC_HTTP_ENABLED=true
       - KC_DB=postgres
       - KC_DB_USERNAME=keycloak
       - KC_DB_PASSWORD=keycloak
       - KC_DB_URL_HOST=postgresql
       - KC_DB_URL_PORT=5432
       - KC_DB_URL_DATABASE=keycloak
       - KEYCLOAK_CREATE_ADMIN_USER=true
       - KEYCLOAK_LOGLEVEL=DEBUG 
         
         #- KEYCLOAK_ADMIN=admin
         # - KEYCLOAK_ADMIN_PASSWORD=password 
       - HTTP_ENABLED=true

      depends_on:
        - postgresql
          #ports:
          #- "80:8080"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.keycloak.rule=Host(`${WIKI_HOST}`)"
        - "traefik.http.routers.keycloak.entrypoints=web"
        - "traefik.http.middlewares.keycloak-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.keycloak.middlewares=keycloak-https-redirect"
        - "traefik.http.routers.keycloak-secure.entrypoints=websecure"
        - "traefik.http.routers.keycloak-secure.rule=Host(`${WIKI_HOST}`)"
        - "traefik.http.routers.keycloak-secure.tls=true"
        - "traefik.http.routers.keycloak-secure.service=keycloak"
        - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
        - "traefik.http.routers.keycloak-secure.tls=true"
        - "traefik.docker.network=proxy-net"
      networks:
        - proxy-net
networks:
  proxy-net:
