version: "3.3"

name: bs-dev

services:
  web:
    image: bluespice/dev-web-free:${VERSION}
    volumes:
      - ${DEV_APP_CODEBASE_DIR}:/opt/bluespice/w
  task:
    image: bluespice/dev-task-free:${VERSION}
    volumes:
      - ${DEV_APP_CODEBASE_DIR}:/opt/bluespice/w
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://search:9200"]'
      
# TODO: Add Test SAML-IdP and Test-OpenIDConnect-provider