services: 

  collabpads:
    image: bluespice/collabpads:${VERSION}
    environment:
      COLLABPADS_BACKEND_WIKI_BASEURL: http://wiki-web:9090
      COLLABPADS_BACKEND_MONGO_DB_HOST: collabpads-database
      COLLABPADS_BACKEND_MONGO_DB_PORT: 27017
      COLLABPADS_BACKEND_LOG_LEVEL: info
      COLLABPADS_BACKEND_PORT: 8081
      VIRTUAL_HOST: ${WIKI_HOST}
      VIRTUAL_PATH: /_collabpads/
      VIRTUAL_PORT: 8081

  collabpads-database:
    image: mongo:5.0-focal
    volumes:
      - ${DATADIR}/database-collabpads:/data/db

