name: bluespice

x-common-environment: &common-environment
  VERSION: ${VERSION}
  EDITION: ${EDITION}
  BACKUP_HOUR: ${BACKUP_HOUR}

  WIKI_NAME: ${WIKI_NAME}
  WIKI_LANG: ${WIKI_LANG}
  WIKI_PASSWORDSENDER: ${WIKI_PASSWORDSENDER}
  WIKI_EMERGENCYCONTACT: ${WIKI_EMERGENCYCONTACT}
  WIKI_HOST: ${WIKI_HOST}
  WIKI_PORT: ${WIKI_PORT}
  WIKI_PROTOCOL: ${WIKI_PROTOCOL}

  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  DB_HOST: ${DB_HOST}
  DB_NAME: ${DB_NAME}
  DB_PREFIX: ${DB_PREFIX}
  SMTP_HOST: ${SMTP_HOST}
  SMTP_PORT: ${SMTP_PORT}
  SMTP_USER: ${SMTP_USER}
  SMTP_PASS: ${SMTP_PASS}
  SMTP_ID_HOST: ${SMTP_ID_HOST}

services:
  wiki-web:
    image: docker.bluespice.com/bluespice-${EDITION}/wiki:${VERSION}
    environment:
      <<: *common-environment
    command: start-web

    volumes:
      - ${DATADIR}/wiki:/data

  wiki-task:
    image: docker.bluespice.com/bluespice-${EDITION}/wiki:${VERSION}
    command: ["start-task --runAll"]
    environment:
      <<: *common-environment
    volumes:
      - ${DATADIR}/wiki:/data
