version: "3.7"

services:

  wiki-web:
    command:
      - /app/bin/setup-dev && /app/bin/start-web
    volumes:
      - ${DEV_WIKI_CODEBASE_DIR}:/opt/bluespice/w

  wiki-task:
    command:
      - /app/bin/setup-dev && /app/bin/start-task
    volumes:
      - ${DEV_WIKI_CODEBASE_DIR}:/opt/bluespice/w

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  dbadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:8080"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://search:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true

  collabpadsbackend:
    environment:
      COLLABPADS_BACKEND_LOG_LEVEL: debug

# TODO: Add Test SAML-IdP and Test-OpenIDConnect-provider