services: 

  collabpads:
    image: bluespice/collabpads:${VERSION}
    environment:
      COLLABPADS_BACKEND_WIKI_BASEURL: http://wiki-web:9090
      COLLABPADS_BACKEND_MONGO_DB_HOST: collabpads-database
      COLLABPADS_BACKEND_MONGO_DB_PORT: 27017
      COLLABPADS_BACKEND_LOG_LEVEL: info
      COLLABPADS_BACKEND_PORT: 8081
    labels:  
      - "traefik.http.routers.collabpads.rule=Host(`${WIKI_HOST}`)&&PathPrefix(`/_collabpads`)"
      - "traefik.http.middlewares.collabpadspathstrip.stripprefix.prefixes=/_collabpads"
      - "traefik.http.routers.collabpads.entrypoints=websecure"
      - "traefik.http.routers.collabpads.middlewares=collabpadspathstrip"
      - "traefik.http.services.collabpads.loadbalancer.server.port=8081"
      - "traefik.http.routers.collabpads.tls=true"
  collabpads-database:
    image: mongo:8.0
    volumes:
      - ${DATADIR}/database-collabpads:/data/db

