version: "3.7"

services:

  proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "443:443"
    volumes:
      - ${DATADIR}/nginx/conf.d:/etc/nginx/conf.d
      - ${DATADIR}/nginx/vhost.d:/etc/nginx/vhost.d
      - ${DATADIR}/nginx/html:/usr/share/nginx/html
      - ${DATADIR}/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.nginx-proxy.nginx=true

  wiki-web:
    environment:
      VIRTUAL_HOST: ${WIKI_HOST}
