version: "3.7"

services:

  wiki-web:
    command:
      - setup-dev && start-web
    volumes:
      - ${DEV_WIKI_CODEBASE_DIR}:/app/bluespice/w

  wiki-task:
    command:
      - setup-dev && start-task
    volumes:
      - ${DEV_WIKI_CODEBASE_DIR}:/app/bluespice/w

  collabpadsbackend:
    environment:
      COLLABPADS_BACKEND_LOG_LEVEL: debug

  dev-mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    environment:
      VIRTUAL_HOST: ${WIKI_HOST}
      VIRTUAL_PORT: 8025
      VIRTUAL_PATH: /_mailhog

  dev-dbadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
      PMA_ABSOLUTE_URI: ${WIKI_PROTOCOL}://${WIKI_HOST}/_dbadmin
      VIRTUAL_HOST: ${WIKI_HOST}
      VIRTUAL_PATH: /_dbadmin

  dev-searchdashboards:
    image: opensearchproject/opensearch-dashboards:2
    environment:
      OPENSEARCH_HOSTS: '["http://search:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
      VIRTUAL_HOST: ${WIKI_HOST}
      VIRTUAL_PORT: 5601
      VIRTUAL_PATH: /_searchdashboards

  dev-mongodbadmin:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://collabpadsbackend-database:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
      ME_CONFIG_SITE_BASEURL: /_mongodbadmin
      VIRTUAL_HOST: ${WIKI_HOST}
      VIRTUAL_PORT: 8081
      VIRTUAL_PATH: /_mongodbadmin

  dev-ldapserver:
    # See https://github.com/rroemhild/docker-test-openldap
    image: ghcr.io/rroemhild/docker-test-openldap:master
    ports:
      - "10389:10389"
      - "10636:10636"
    #volumes:
      # Additional volume delcarations required, see https://github.com/rroemhild/docker-test-openldap/blob/2645f2164ffb51ec4b5b4a9af0065ad7f2ffc1cf/Dockerfile#L34
      #- ${DATADIR}/ldap/etc/ldap/slapd.d:/etc/ldap/slapd.d
      #- ${DATADIR}/ldap/etc/ldap/ssl:/etc/ldap/ssl
      #- ${DATADIR}/ldap/var/lib/ldap:/var/lib/ldap
      #- ${DATADIR}/ldap/run/slapd:/run/slapd
      #- ${DATADIR}/ldap/opt/openldap/bootstrap/data:/opt/openldap/bootstrap/data
    profiles:
      - ldap

  dev-openidprovider:
    image: qlik/simple-oidc-provider:latest
    environment:
      - REDIRECTS=https://${WIKI_HOST}/wiki/Special:PluggableAuthLogin
      - PORT=80
      - IDP_NAME=${OIDC_PROVIDER_URL}
      - VIRTUAL_HOST=${OIDC_PROVIDER_HOST}
      - CONFIG_FILE=/data/config.json
      - USERS_FILE=/data/users.json
    volumes:
      - ${DATADIR}/oidc:/data
    extra_hosts:
      - "${WIKI_HOST}:host-gateway"
    profiles:
      - oidc

  dev-s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${DATADIR}/s3:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: HalloWelt11
    command: server /data --console-address ":9001"
    profiles:
      - s3
    
  dev-samlidp:
    image: kristophjunge/test-saml-idp
    volumes:
      - ${DEV_WIKI_CODEBASE_DIR}/saml-config.php:/var/www/simplesamlphp/config/config.php
      - ${DEV_WIKI_CODEBASE_DIR}/saml-users.php:/var/www/simplesamlphp/config/authsources.php
      - ${DEV_WIKI_CODEBASE_DIR}/saml-sp-metadata.php:/var/www/simplesamlphp/metadata/saml20-sp-remote.php
    environment:
      VIRTUAL_HOST: ${DEV_IDP_HOST}
      VIRTUAL_PORT: 8080
      DEV_IDP_HOST: ${DEV_IDP_HOST}
      DEV_SP_HOSTS: ${DEV_SP_HOST}
    profiles:
      - saml


