version: "3.7"

services:

  search:
    image: bluespice/search:${VERSION}
    volumes:
      - ${DATADIR}/search:/usr/share/opensearch/data
    healthcheck:
      test: curl -f http://localhost:9200
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  database:
    image: mariadb:10.5
    volumes:
      - ${DATADIR}/mariadb/data:/var/lib/mysql
      - ${DATADIR}/mariadb/logs:/var/log/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASS}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MARIADB_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  wiki-web:
    depends_on:
        database:
            condition: service_healthy
        search:
            condition: service_healthy
  wiki-task:
    depends_on:
        database:
            condition: service_healthy
        search:
            condition: service_healthy