version: "3.7"

services:

  wiki-web:
    command:
      - setup-dev && start-web
    volumes:
      - ${DEV_WIKI_CODEBASE_DIR}:/app/bluespice/w

  wiki-task:
    command:
      - setup-dev && start-task
    volumes:
      - ${DEV_WIKI_CODEBASE_DIR}:/app/bluespice/w

  dev-mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  dev-dbadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:8080"

  dev-searchdashboards:
    image: opensearchproject/opensearch-dashboards:2
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://search:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true

# TODO: Add Test SAML-IdP and Test-OpenIDConnect-provider