version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "5.3.x"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "5.2.x"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "5.1.x"
    schedule:
      interval: "weekly"
